spring:
  application:
    name: progen

  datasource:
    url: jdbc:mysql://localhost:3306/progen
    username: admin
    password: dev@9199

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 3300

shared:
  auth-filter:
    jwt-secret-key: thiskeyisfortestpurposeonlynotintededtouseinproductionenvironmentandotheraspectsalltogetherwillbechangedinfuture
    public-endpoints:
      - /auth/*
    secured-endpoints:
      - /api/v1/*
    user-details-service-class: dev.monorepo.apps.progen.service.UserAuthService

